[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Set in order to use transient storage
solc_version = "0.8.26"
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

# Temporary fix for "multiple matching artifacts found" error
unchecked_cheatcode_artifacts = true
